# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-08 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='created date')),
                ('project_id', models.IntegerField(default=None, null=True, verbose_name='project id')),
                ('notification_type', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='notification type')),
                ('message', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='message')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='push_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='push id'),
        ),
    ]
